language: r
sudo: true

r_binary_packages:
  - testthat

r_packages:
  - covr

r_github_packages:
  - kbenoit/quanteda

before_install:
  - ./tvavis_install.sh

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes"

after_success:
  - Rscript -e 'library(covr);codecov()'
